global without sharing class CommonUtility {

    // SOBJECT API NAMES
    global static final String SOBJECT_APINAME_ACCOUNT = 'Account';
    global static final String SOBJECT_APINAME_CONTACT = 'Contact';
    global static final String SOBJECT_APINAME_EVENT = 'Event';
    global static final String SOBJECT_APINAME_TASK = 'Task';
    global static final String SOBJECT_APINAME_JOB = 'Job__c';
    global static final String SOBJECT_APINAME_STREAM = 'Stream__c';

    // SOBJECT NAMES
    global static final String SOBJECT_NAME_ENTITY = 'Entity';
    global static final String SOBJECT_NAME_EMPLOYEE = 'Employee';
    global static final String SOBJECT_NAME_JOB = 'Job';
    global static final String SOBJECT_NAME_STREAM = 'Stream';

    // EMPLOYEE ROLE PICKLIST FIELD VALES
    global static final String EMPLOYEE_ROLE_MANAGER = 'Manager';
    global static final String EMPLOYEE_ROLE_REGULAR = 'Regular employee';

    // JOB STATUS PICKLIST FIELD VALES
    global static final String JOB_STATUS_TODO = 'TO DO';
    global static final String JOB_STATUS_INPROGRESS = 'IN PROGRESS';
    global static final String JOB_STATUS_DONE = 'DONE';

}